[package]
org = "wso2"
name = "transactional_template_flow"
version = "0.1.0"
distribution = "2201.12.6"

[[dependency]]
org = "ballerinax"
name = "mailchimp.transactional"
version = "1.0.0"
repository="local"

[build-options]
observabilityIncluded = true
