[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "mailchimp.transactional"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["mailchimp","transactional","email","email-connector","ballerina","ballerina-connector","campaigns"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-mailchimp.transactional"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
